services:
  # Backend API Service
  - type: web
    name: cell-dynamics-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn advanced_cell_backend:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        generateValue: true
    healthCheckPath: /api/health
